version: "2"
checks:
  similar-code:
    config:
      threshold: 100
exclude_patterns:
    - 'tests/'
    - 'spec/'
    - '**/*.spec.tsx'
    - '**/*.spec.ts'
    - '**/*.spec.js'
    - '**/vendor/'
    - '**/node_modules/'
